### ISSUE TITLE
Uncaught ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by johnbaoss** [aegir-assembly/omni-clip#13]
Uncaught ReferenceError: SharedArrayBuffer is not defined
    at worker-browser.js:548:46
    at worker-browser.js:6397:35
    at worker-browser.js:6399:3

**Comment by johnbaoss** [comment]
I want to use it in Vite+Vue3+nuxt3, but it is reporting this error.
Google Chrome：127.0.6533.100  (arm64) ,Mac Mini M2.
