### ISSUE TITLE
[!] RollupError: Invalid value for option "output.file" 

### ISSUE THREAD

**Issue by johnbaoss** [aegir-assembly/omni-clip#16]
root@milvus:/www/wwwroot/omniclip# npm run build

> omniclip@1.0.7 build
> turtle-standard && run-p copy-coi copy-assets

x/main.js → x/main.bundle.js...
(!) "this" has been rewritten to "undefined"
https://rollupjs.org/troubleshooting/#error-this-is-undefined
node_modules/@benev/slate/x/element/silver.js
1: var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
                                 ^
2:     if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
3:     if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot re...
...and 3 other occurrences
node_modules/@benev/slate/x/element/gold.js
1: var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, state, value, kind, f) {
                                 ^
2:     if (kind === "m") throw new TypeError("Private method is not writable");
3:     if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a setter");
...and 3 other occurrences
node_modules/@benev/slate/x/base/helpers/mixin.js
1: var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
                                 ^
2:     if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
3:     if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot re...
...and 3 other occurrences

...and 50 other files
(!) [plugin node-resolve] Could not resolve import "mediainfo.js/dist/esm-bundle/index.min.js" in /www/wwwroot/omniclip/x/context/controllers/media/controller.js using exports defined in /www/wwwroot/omniclip/node_modules/mediainfo.js/package.json.
(!) [plugin node-resolve] Could not resolve import "fabric/dist/fabric.mjs" in /www/wwwroot/omniclip/x/context/controllers/compositor/controller.js using exports defined in /www/wwwroot/omniclip/node_modules/fabric/package.json.
(!) [plugin node-resolve] Could not resolve import "ffprobe-wasm/browser.mjs" in /www/wwwroot/omniclip/x/context/controllers/video-export/helpers/FFmpegHelper/helper.js using exports defined in /www/wwwroot/omniclip/node_modules/ffprobe-wasm/package.json.
(!) [plugin node-resolve] Could not resolve import "@ffmpeg/ffmpeg/dist/esm/index.js" in /www/wwwroot/omniclip/x/context/controllers/video-export/helpers/FFmpegHelper/helper.js using exports defined in /www/wwwroot/omniclip/node_modules/@ffmpeg/ffmpeg/package.json.
(!) [plugin node-resolve] Could not resolve import "@ffmpeg/util/dist/esm/index.js" in /www/wwwroot/omniclip/x/context/controllers/video-export/helpers/FFmpegHelper/helper.js using exports defined in /www/wwwroot/omniclip/node_modules/@ffmpeg/util/package.json.
(!) [plugin node-resolve] Could not resolve import "fabric/dist/index.mjs" in /www/wwwroot/omniclip/x/context/controllers/compositor/parts/image-manager.js using exports defined in /www/wwwroot/omniclip/node_modules/fabric/package.json.
(!) [plugin node-resolve] Could not resolve import "fabric/dist/index.mjs" in /www/wwwroot/omniclip/x/context/controllers/compositor/parts/text-manager.js using exports defined in /www/wwwroot/omniclip/node_modules/fabric/package.json.
(!) [plugin node-resolve] Could not resolve import "fabric/dist/index.mjs" in /www/wwwroot/omniclip/x/context/controllers/compositor/parts/video-manager.js using exports defined in /www/wwwroot/omniclip/node_modules/fabric/package.json.
(!) [plugin node-resolve] Could not resolve import "fabric/dist/fabric.mjs" in /www/wwwroot/omniclip/x/context/controllers/compositor/lib/aligning_guidelines.js using exports defined in /www/wwwroot/omniclip/node_modules/fabric/package.json.
(!) [plugin node-resolve] Could not resolve import "@ffmpeg/util/dist/esm/index.js" in /www/wwwroot/omniclip/x/context/controllers/timeline/parts/waveform.js using exports defined in /www/wwwroot/omniclip/node_modules/@ffmpeg/util/package.json.
(!) [plugin node-resolve] Could not resolve import "web-demuxer/dist/web-demuxer.js" in /www/wwwroot/omniclip/x/tools/demuxer.js using exports defined in /www/wwwroot/omniclip/node_modules/web-demuxer/package.json.
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
mediainfo.js/dist/esm-bundle/index.min.js (imported by "x/context/controllers/media/controller.js")
fabric/dist/fabric.mjs (imported by "x/context/controllers/compositor/controller.js" and "x/context/controllers/compositor/lib/aligning_guidelines.js")
ffprobe-wasm/browser.mjs (imported by "x/context/controllers/video-export/helpers/FFmpegHelper/helper.js")
@ffmpeg/ffmpeg/dist/esm/index.js (imported by "x/context/controllers/video-export/helpers/FFmpegHelper/helper.js")
@ffmpeg/util/dist/esm/index.js (imported by "x/context/controllers/video-export/helpers/FFmpegHelper/helper.js" and "x/context/controllers/timeline/parts/waveform.js")
fabric/dist/index.mjs (imported by "x/context/controllers/compositor/parts/image-manager.js", "x/context/controllers/compositor/parts/text-manager.js" and "x/context/controllers/compositor/parts/video-manager.js")
web-demuxer/dist/web-demuxer.js (imported by "x/tools/demuxer.js")
[!] RollupError: Invalid value for option "output.file" - when building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
https://rollupjs.org/configuration-options/#output-dir
    at getRollupError (/www/wwwroot/omniclip/node_modules/rollup/dist/shared/parseAst.js:282:41)
    at Object.error (/www/wwwroot/omniclip/node_modules/rollup/dist/shared/parseAst.js:278:42)
    at validateOptionsForMultiChunkOutput (/www/wwwroot/omniclip/node_modules/rollup/dist/shared/rollup.js:19675:28)
    at Bundle.generate (/www/wwwroot/omniclip/node_modules/rollup/dist/shared/rollup.js:19566:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /www/wwwroot/omniclip/node_modules/rollup/dist/shared/rollup.js:21204:27
    at catchUnfinishedHookActions (/www/wwwroot/omniclip/node_modules/rollup/dist/shared/rollup.js:20676:16)
    at async Promise.all (index 0)
    at build (/www/wwwroot/omniclip/node_modules/rollup/dist/bin/rollup:1598:5)
    at runRollup (/www/wwwroot/omniclip/node_modules/rollup/dist/bin/rollup:1710:21)

🐢 @benev/turtle
copied s/index.css --> x/index.css
copied s/tools/mp4boxjs/mp4box.js --> x/tools/mp4boxjs/mp4box.js
copied s/icons/remix-icon/LICENSE.md --> x/icons/remix-icon/LICENSE.md
copied s/icons/material-design-icons/LICENSE.md --> x/icons/material-design-icons/LICENSE.md
copied s/icons/gravity-ui/LICENSE.md --> x/icons/gravity-ui/LICENSE.md
copied s/icons/carbon-icons/LICENSE.md --> x/icons/carbon-icons/LICENSE.md
copied s/context/controllers/timeline/bbb_video_avc_frag.mp4 --> x/context/controllers/timeline/bbb_video_avc_frag.mp4
copied s/context/controllers/compositor/lib/license.md --> x/context/controllers/compositor/lib/license.md
copied s/components/omni-timeline/views/media-player/bbb_video_avc_frag.mp4 --> x/components/omni-timeline/views/media-player/bbb_video_avc_frag.mp4
rendered x/index.html.js --> x/index.html

> omniclip@1.0.7 copy-assets
> cp -r assets x/

> omniclip@1.0.7 copy-coi
> cp node_modules/coi-serviceworker/coi-serviceworker.js x/

root@milvus:/www/wwwroot/omniclip# npm install

up to date in 2s

161 packages are looking for funding
  run `npm fund` for details

**Comment by johnbaoss** [comment]
Ubuntu 22.04.4 LTS (Jammy Jellyfish) x86_64(Py3.7.8)
